<?xml version="1.0" encoding="ISO-8859-1" ?>

<!-- Employees with an embedded DTD file  -->

<!DOCTYPE corporation [ 
<!ELEMENT employee (name, number, projects)>

<!ATTLIST employee
	id CDATA #IMPLIED
>

<!ELEMENT name (#PCDATA)>
<!ELEMENT number (#PCDATA)>

<!ELEMENT projects (project)*>
<!ELEMENT project (#PCDATA)>

<!ENTITY ouml "o">
]>

<corporation>
	<employee id="2">
		<name>B&ouml;b
		</name>
		<number>423</number>
		<projects>
			<project>A</project>
			<project>B</project>
		</projects>
	</employee>
</corporation>